// apps/react/src/List.jsx
import { memo, useEffect, useState } from 'react';

let currentLength = 100;

function List({ items }) {
	const [ shownItems, setShownItems ] = useState([]);

	useEffect(() => setShownItems(items.slice(0, 100)), [ items ]);

	useEffect(() => {
		if (!items.length) return;

		function onScroll() {
			if (!items.length) return;

			if (document.scrollingElement.scrollTop < (document.scrollingElement.offsetHeight - window.innerHeight - 50)) {
				return;
			}
			if (shownItems.length < items.length) {
				currentLength += 100;
				setShownItems(items.slice(0, currentLength));
			} else {
				document.removeEventListener('scroll', onScroll);
			}
		}

		document.addEventListener('scroll', onScroll)
		return () => document.removeEventListener('scroll', onScroll);
	}, [ items ]);

	return (
		<div>
			{shownItems.map((row) => <div key={row.id}>{row.content}</div>)}
		</div>
	)
}

export default memo(List);

// apps/vue/src/components/List.vue
<template>
	<div>
		<p v-for="row in shownItems" :key="row.id">{{ row.content }}</p>
	</div>
</template>

<script setup>
import { computed, onUnmounted, ref } from 'vue';

const props = defineProps({
	items: Array
})

const length = ref(100);

const shownItems = computed(() => props.items.slice(0, length.value));


function onScroll() {
	if (document.scrollingElement.scrollTop < (document.scrollingElement.offsetHeight - window.innerHeight - 50)) {
		return;
	}
	if (length.value < props.items.length) {
		length.value += 100;
	} else {
		document.removeEventListener('scroll', onScroll);
	}
}

document.addEventListener('scroll', onScroll);
onUnmounted(() => document.removeEventListener('scroll', onScroll));


</script>

<style scoped>

</style>
